### ISSUE TITLE
WindowsImage cache handler is failing when application is being closed.

### ISSUE THREAD

**Issue by pedroafsouza** [microspaze/FFImageLoading.Maui#44]
### Description

Hi guys, during the event of closing the application there is a random exception that has been throwing by the library.  The exception happens on the class CachedImageHandler > UpdateImage. 

### Steps to Reproduce

1. Have an application.
2. Load an image.
3. Close the application.
4. Check your debug output. You might get something like that:
`  at Microsoft.Maui.Handlers.ElementHandler`2.get_PlatformView()
   at Microsoft.Maui.Handlers.WindowHandler.MapRequestDisplayDensity(IWindowHandler handler, IWindow window, Object args)
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
   at Microsoft.Maui.ElementHandlerExtensions.InvokeWithResult[T](IElementHandler handler, String commandName, RetrievePlatformValueRequest`1 args)
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.RequestDisplayDensity()
   at FFImageLoading.Maui.Platform.CachedImageHandler.UpdateImage(Image imageView, CachedImage image, CachedImage previousImage)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()`

### Expected Behavior

1. No exceptions should be throw from the library into the main application.,

### Actual Behavior

1. Exceptions are flowing into the main application.

### Basic Information

- Version with issue: latest

I do have a fix suggestion. Let me know if you guys are open for a pull request. Thank you.

**Comment by microspaze** [comment]
@pedroafsouza  PRs are welcome.

**Comment by pedroafsouza** [comment]
@microspaze I would love to but creating a branch or pushing into a new branch is disabled in your repo. So, I can't.

**Comment by microspaze** [comment]
@pedroafsouza You can just fork the main branch of this repository and push your changes to your fork repository. Then you can create a pull request to the original repository and I will review the code to verify the merge request.

**Comment by pedroafsouza** [comment]
Thanks micropaze. I did it now.

**Comment by pedroafsouza** [comment]
I did it. Can you approve so I merge it?

**Comment by pedroafsouza** [comment]
Thanks, could you generate a package with a minor version ?

**Comment by microspaze** [comment]
@pedroafsouza Does this issue block your developing work? If yes, I can release a new version for you. Beacause I'm still working on the issue #47 which is a iOS crush issue and has more higher priority to fix. I'd like to release the new version as soon as posable when #47 issue fixed.

**Comment by microspaze** [comment]
I'm so sorry for the issue blocking. I will release a new version today.

**Comment by microspaze** [comment]
@pedroafsouza The latest version 1.2.7 has been uploaded to Nuget.

**Comment by pedroafsouza** [comment]
Thanks @microspaze, it is working now. I think we can close the issue.
