### ISSUE TITLE
App Crashed when CachedImage changes size in not visible state. IOS

### ISSUE THREAD

**Issue by DmitryNikiforovCoherent** [microspaze/FFImageLoading.Maui#46]
### Description
If CachedImage loaded and start download image by url, it can throw exception after download finish and image try to fit size. It seems, something changes on maui, this works correctly on maui 8.0.40, but start crashing from 8.0.60

### Steps to Reproduce

Open screen with CachedImage, immediately after that hide(in my case we have custom tab behavior, switching to the another tab cause crash)

### Expected Behavior
Application doesn't crash

### Actual Behavior
Application crashes with stacktrace

`Failed to marshal the Objective-C object 0x11ef7ad40 (type: Microsoft_Maui_Platform_LayoutView). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Platform.LayoutView' does not have a constructor that takes one NativeHandle argument).
   at ObjCRuntime.Runtime.MissingCtor(IntPtr , IntPtr , Type , MissingCtorResolution , IntPtr , RuntimeMethodHandle )
   at ObjCRuntime.Runtime.ConstructNSObject[UIView](IntPtr , Type , MissingCtorResolution , IntPtr , RuntimeMethodHandle )
   at ObjCRuntime.Runtime.GetNSObject[UIView](IntPtr , IntPtr , RuntimeMethodHandle , Boolean )
   at ObjCRuntime.Runtime.GetNSObject[UIView](IntPtr , IntPtr , RuntimeMethodHandle )
   at ObjCRuntime.Runtime.GetNSObject[UIView](IntPtr )
   at UIKit.UIView.get_Superview()
   at Microsoft.Maui.Platform.MauiView.SetNeedsLayout()
   at Microsoft.Maui.Platform.MauiView.SetNeedsLayout()
   at Microsoft.Maui.Handlers.ViewHandler.MapInvalidateMeasure(IViewHandler handler, IView view, Object args)
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o)
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
   at Microsoft.Maui.Controls.VisualElement.InvalidateMeasureOverride()
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.InvalidateMeasure()
   at Microsoft.Maui.Controls.VisualElement.InvalidateMeasureInternal(InvalidationTrigger trigger)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IVisualElementController.InvalidateMeasure(InvalidationTrigger trigger)
   at FFImageLoading.Maui.Platform.CachedImageHandler.<>c__DisplayClass15_0.<ImageLoadingSizeChanged>b__0()
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass1_0.<DispatchAsync>b__0()
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass0_0`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<DispatchAsync>b__0()
--- End of stack trace from previous location ---
   at FFImageLoading.Maui.Platform.CachedImageHandler.ImageLoadingSizeChanged(CachedImage element, Boolean isLoading)`

### Basic Information

- Version with issue: 1.2.1 - 1.2.6
- Last known good version: Unknown
- Platform: IOS

### Screenshots

https://github.com/user-attachments/assets/d65861a8-c091-4c11-b931-d35ac7b1bda3

### Reproduction Link / Code

[MauiApp.zip](https://github.com/user-attachments/files/16579382/MauiApp.zip)

**Comment by DmitryNikiforovCoherent** [comment]
Maui issue https://github.com/dotnet/maui/issues/24032
